### ISSUE TITLE
Virus identified I-Worm/Nuwar.L in mediacenterjs.exe

### ISSUE THREAD

**Issue by Rubenvanhoeyveld** [jansmolders86/mediacenterjs#149]
Not sure if this is normal...

![2014-10-19 16_49_34-](https://cloud.githubusercontent.com/assets/3180443/4693505/3d4eca22-579f-11e4-866a-91235d8a554c.png)

**Comment by jansmolders86** [comment]
should this come up, please read:  https://github.com/jansmolders86/mediacenterjs/wiki/User-manual:-FAQ#im-getting-a-virus-or-unknown-publisher-warning-on-windows
