### ISSUE TITLE
New movie directive does not iterate 

### ISSUE THREAD

**Issue by jansmolders86** [jansmolders86/mediacenterjs#180]
Hey Jonathan,

I've found an issue with the new movie directive. For some reason, it does not iterate and only shows one movie. So in my test scenario I have 70 movies in my library (database confirms this) but I only see one.
I haven't found the issue myself yet so I'm reaching out to you :) I'll continue to look though!

I also have an issue with the Music app btw. It doesn't group tracks in the album view anymore. I'm looking into it as well. 

Thanks in advance!

**Comment by Jon889** [comment]
It seems to be something on the server side, it worked fine until I cleared the cache also /movies/load is only showing one result

**Comment by jansmolders86** [comment]
That was what I was afraid of. I couldn't find a direct reason in the code. TMDB does have some fair use limitations. It might be we've run into that limit. I'll investigate further! Thanks for checking it out!

**Comment by Jon889** [comment]
I think only one of my movies has a title that can be found on TMDB (the rest have a load of junk in the title), and by the code it seems the movie is only added to the database if the movie is found. I think this is because or the changes @hoffi made?

**Comment by hoffi** [comment]
You are right, @Jon889.
Seems to be a mistake by me in the Movies and TV Metadata-Processors.
Whenever no result or an error was return from TMDB, the movie or show is not added to database.

I'll look into that

**Comment by hoffi** [comment]
@Jon889 @jansmolders86 can you try again?

**Comment by Jon889** [comment]
That works for me :)

**Comment by jansmolders86** [comment]
Dito! Thanks so much!

**Comment by jansmolders86** [comment]
BTW @hoffi & @Jon889 I would like to suggest we introduce a develop branch.

I was thinking we should have a master branch that's always as stable as possible and release to it on specific moments (eg, feature release)

We already create new features in a feature branch  so once we're done, we can merge that feature into develop to check if everything works as expected. Especially since you guys are on Mac and I'm on Windows, that should give us some nice test scenarios. 

Then once we give the all clear, one of us releases into Master.
This might seem a bit heavy at first, but will ensure stable code for new users coming in.

Are you guys game for this approach?

Thanks!

**Comment by hoffi** [comment]
@jansmolders86 Sure.
So you mean no more commit should be pushed to `master` except merges from `develop` to `master`?
Would definitely be better as you can be sure then, that `master` branch is always stable.

**Comment by jansmolders86** [comment]
Exactly! :) Let's make it effective from this moment forward! The  Develop branch has already been added. Users can decide for themselves if they want to check out the stable master or the newer potential unstable develop branch!
