### ISSUE TITLE
Code-Style

### ISSUE THREAD

**Issue by hoffi** [jansmolders86/mediacenterjs#188]
Define JSHint rules and use it to avoid bad code and bad formatting. 

Maybe also add a [EditorConfig](http://editorconfig.org) to ensure everyone uses same indentation, encoding and newline settings?

We could also use [Travis-CI](http://travis-ci.org) to validate these rules on every commit and pull request.

**Comment by jansmolders86** [comment]
Done in commit: https://github.com/jansmolders86/mediacenterjs/commit/d56c5d06c9b27e7cbc5e7cf269fa1d40de070071
Feel free to alter or change ;)

**Comment by hoffi** [comment]
Nice :)
