### ISSUE TITLE
.green.bold throws exception

### ISSUE THREAD

**Issue by matita** [jansmolders86/mediacenterjs#195]
The first time I installed mediacenterjs on Windows 7 and I started it, it immediately crashed throwing exception on `server.js line 110`, saying cannot access `bold` property of null.
I commented `.green.bold`, restarted mediacenter.exe, played with it a bit, upgraded it as requested in the GUI and the `.green.bold` is there again, but now it is working (maybe that line is never called or the downloaded version was buggy and the updated one not?).
I downloaded the windows build with exe yesterday, maybe it is a buggy build?

**Comment by jansmolders86** [comment]
Thanks for letting me know! I fixed it in the github master. Will build a new version for the installer asap!
