### ISSUE TITLE
Error on YouTube app

### ISSUE THREAD

**Issue by matita** [jansmolders86/mediacenterjs#198]
On a fresh installation, when I access the YouTube app I can only see a white page with an arrow to go back to the home page.
The console logs `error: Error searching Youtube`
By inspecting the code it seems like the app expects the OAuth token to be initialized.

Possible solutions/to do could be:
* prompt the user to log in with YouTube, either by providing a *Register OAuth* button or redirecting to the Settings page with a link to `/settings/#oauthContainer`
* give user feedback on failed ajax calls

**Comment by matita** [comment]
Possible solution could also be showing some generic videos and warning the user he/she is not logged in

**Comment by jansmolders86** [comment]
There should be a prompt automatically but this might tie in with issue #199

**Comment by lucienimmink** [comment]
Are you using the new V3 YouTube API @jansmolders86 ?
Google decided to drop support for V2 and lower so you might need to upgrade the code.

**Comment by jansmolders86** [comment]
No I'm not Lucien, thanks for the tip! I'll check it out.
How's life btw? :) feel free to write me an email or ping me on Hangouts to chat!

**Comment by jansmolders86** [comment]
The Youtube app needs to be refactored so it only depends on the Youtube api and does not use any user specific details requiring Oauth v2.
