### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by matita** [jansmolders86/mediacenterjs#199]
When clicking on Settings/Register OAuth a popup opens with this error by Google, preventing logging in with Google account:

```
401. That’s an error.

Error: deleted_client

The OAuth client was deleted.

Request Details
scope=https://www.googleapis.com/auth/youtubepartner
response_type=code
redirect_uri=https://oauth.io/auth
state=1vIikQTrToHOD5Lo0jQGINMoRxc
client_id=783787535520.apps.googleusercontent.com
That’s all we know.
```

**Comment by jansmolders86** [comment]
Google has ditched oauth in favour of oauth2. I'm stepping away from using oauth as a whole for now as only the Youtube app actually uses it. I want to refactor the youtube app to make it behave more like the Youtube app on the xbox for instance.
