### ISSUE TITLE
Unexpected end of input when loading tv

### ISSUE THREAD

**Issue by ipacheco-uy** [jansmolders86/mediacenterjs#202]
Hi, i am using MediaCenter for some days and although the movie tab is working fine, when i enter TV tab the server crash..

![mdjs](https://cloud.githubusercontent.com/assets/12069039/7952289/1200d160-098a-11e5-9ed5-34c9030b8ad9.PNG)

Could it be because of the size of the file that is loading? The one it is loading first is 1.72gb 

Thanks

**Comment by hoffi** [comment]
Stacktrace is pointing to trakt module.
Maybe the trakt API has changed?

**Comment by jansmolders86** [comment]
Afraid so:

"V1 API End of Life.
The V1 API will go offline on June 30, 2015. For more info, please read this post."

http://docs.trakt.apiary.io/#introduction/create-an-app

I'll have to see whats changed or if we can find a teplacement
