### ISSUE TITLE
Handle request limit of 40 every 10 seconds in movies app!

### ISSUE THREAD

**Issue by jansmolders86** [jansmolders86/mediacenterjs#203]

**Comment by andreme** [comment]
I was about to fix this, but I'm waiting for my other PR to be accepted.

**Comment by jansmolders86** [comment]
I would be so grateful if you did man :) I'll take a look at your PR to speed things up

**Comment by jansmolders86** [comment]
Hey @andreme, I'm curious how you would solve this one the :)
