### ISSUE TITLE
What file structure can MCJS handle for TV shows?

### ISSUE THREAD

**Issue by haarts** [jansmolders86/mediacenterjs#214]
I've taken a look at the code and it seems that MCJS expects everything to be in 1 directory. Although I see some handling of sub directories in the form of 'show name - season n/'. But it doesn't seem to handle 'show name/n/'. 
Before I inspect all the permutations I figured I'd just ask.

**Comment by jansmolders86** [comment]
The directories should match the description you see here: https://github.com/jansmolders86/mediacenterjs/wiki/User-manual:-Guidelines-media-library#directory-conventions
