### ISSUE TITLE
Movie metadata query issue

### ISSUE THREAD

**Issue by mnzt** [jansmolders86/mediacenterjs#217]
```
server-2 (out): Executing (default): SELECT `id`, `filePath`, `title`, `posterURL`, `backgroundURL`, `imdbID`, `rating`, `certification`, `genre`, `runtime`, `overview`, `cdNumber`, `adult`, `year`, `hidden` FROM `Movies` AS `Movie`;
server-2 (out): info: Screen ready...
server-2 (out): Error retrieving data for Trainwreck  UNRATED null
server-2 (out): Error retrieving data for  { [Error: cannot GET /3/search/movie?api_key=1d0a02550b7d3eb40e4e8c47a3d8ffc6&query=&language=en&year= (422)]
server-2 (out):   status: 422,
server-2 (out):   text: '{"errors":["query must be provided"]}',
server-2 (out):   method: 'GET',
server-2 (out):   path: '/3/search/movie?api_key=1d0a02550b7d3eb40e4e8c47a3d8ffc6&query=&language=en&year=' }
```

This is also the case on movies with a lot of info in the folder title, looking at the path, there seems to be an issue with taking the title and querying the API. 

(this is from a fresh install from the repo)

**Comment by mnzt** [comment]
Side note: this also causes the `/movies/` route to hang with `loading, please wait`.

**Comment by jansmolders86** [comment]
That's super weird.. let me dig into this. I didn't get this issue the other day. Just to make sure, are you running the windows or linux version? And which Node version are you using?

**Comment by mnzt** [comment]
Closing due to no longer using this project.
