### ISSUE TITLE
Startup fails

### ISSUE THREAD

**Issue by sarathkcm** [jansmolders86/mediacenterjs#224]
Startup fails with exception  

Cannot find module 'C:\MediacenterJS\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\MediacenterJS\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\MediacenterJS\lib\utils\database-schema.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I have tried installing sqlite3 globally...

Nice application btw, screenshots look really good.

**Comment by sarathkcm** [comment]
Installing sqlite3 locally on C:\MediacenterJs worked [though is is expected of the MediacenterJS installer to take care of this installation]. 

Good work on the application...

**Comment by thinkbig1979** [comment]
I have a problem starting the application as well:

Here's the output:
```
npm WARN mediacenterjs@0.1.3 license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osboxes/mediacenterjs/npm-debug.log

```

**Comment by tracker1** [comment]
Can you go into a clean directory, and do an `npm i sqlite@3.0.5` see if you get the same error, also try just doing `npm i sqlite3` on its' own, which will give you the latest.  if sqlite3 by itself installs... try updating package.json to change the `3.0.5` for sqlite3 to `~3.1.4` it could be needed for the newer node version you're using...

*Just suggestions, I'm not currently running this application.*

**Comment by thinkbig1979** [comment]
@tracker1 
I tried your suggestions and the `npm i sqlite3` in a clean directory worked, so I went in and deleted the sqlite3 directory from the /mediacenterjs/node_modules directory and removed the sql line from package.json. Then ran `npm i sqlite3` from in the /mediacenterjs/ directory with succes. After that the app started up.

Many thanks for your help!

**Comment by tracker1** [comment]
@thinkbig1979 glad it worked for you.

@jansmolders86 should bump the `sqlite3` reference in package.json to `~3.1.4`, which is the current version.

**Comment by jay3702** [comment]
I had this issue as well. I ran the npm i sqlite3 command and then replaced the existing sqlite subdir with the corresponding dir from the new copy. That worked. No other modifications were required. This was done in a Windows 10 computer. 


BTW - this works quite well on the Xbox One. nice work!
