### ISSUE TITLE
Unable to run make

### ISSUE THREAD

**Issue by pinkman61** [jansmolders86/mediacenterjs#239]
Hi.

I am using Ubuntu 16.04 and following the exhibit mentioned with title:
**Build NodeJS for ARM devices running Ubuntu / Debian**

I am having an issue with the following command.

**sudo ./configure --without-snapshot**

The problem is it is not located where it should be as per instructions and I have to follow the following path: in order to locate the file.

**cd node-v4.2.2-linux-x86/lib/npm**

which is not working either as per error of certain modules not found.
Hence, I cannot sun further commands "make" etc.

request you to reply asap and guide me through the process.

**Comment by th3l0g4n** [comment]
Maybe you are better off using one of the official nodejs builds for ARM which you can download here:
https://nodejs.org/en/download/current/

You may need to google a bit to find out your correct ARM version.
https://raspberrypi.stackexchange.com/questions/9912/how-do-i-tell-which-version-arm-cpu-on-my-pi
https://unix.stackexchange.com/questions/12453/how-to-determine-linux-kernel-architecture
https://unix.stackexchange.com/questions/180726/easy-command-line-method-to-determine-specific-arm-architecture-string

These answers should guide you in the right direction.
