### ISSUE TITLE
NPX should be used on: WIKI: "Developer manual: Start building an app using the app generator"

### ISSUE THREAD

**Issue by BananaAcid** [jansmolders86/mediacenterjs#246]
The whole line about [installing the generator  globally should](https://github.com/jansmolders86/mediacenterjs/wiki/Developer-manual:-Start-building-an-app-using-the-app-generator) be changed to:
`$ npx mediacenterjs-plugin-generator` .. for OSX/Linux, as well as for windows

and btw: `mediacenterjs-plugin-init` would probably be more appropriate ...

**Comment by jansmolders86** [comment]
added the npx line , thanks!

**Comment by BananaAcid** [comment]
npx downloads and executes the package, then removes it again. No need for installation. 

The place you added it to the docs should be a few lines further down, right above the code block or as first paragraph in installation, stating that this command makes it useable without any installation.

Comprehensive guide: https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b
